spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/my_test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    cluster:
      nodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384
      max-redirects: 3
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


kafka:
  topic:
    my-topic: my-topic
    my-topic2: my-topic2